# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 000373571536c2595d7195b93cae52ed5c82e4f00ac972192c4abc68d7f9220f293a131a843fe2bcaeca1ccd299dc25d6652408d621d9456b97da739ec84a9e0

test:
  secret_key_base: c60f70478bfb306f05122f58aabcd70b565a23231ad5bdbb0b684eeff97ece4b36f967fa640d6e5d8d437b6a3d74c55652e2284a41eab34f8190f5ccd7207000

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
